[tool.poetry]
name = "whisper-transcription"
version = "0.1.0"
description = ""
authors = ["St√©phane Burwash <sburwash@live.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
